# Automatically generated by configure - do not modify
TARGET_NAME=riscv64
target=riscv64-linux-user
CONFIG_USER_ONLY=y
CONFIG_LINUX_USER=y
QEMU=/home/yecanming/download/qemu-7.0.0/build/qemu-riscv64
CROSS_CC_GUEST_CFLAGS=
