# Automatically generated by configure - do not modify
TARGET_NAME=riscv64
target=riscv64-softmmu
CONFIG_SOFTMMU=y
QEMU=/home/yecanming/download/qemu-7.0.0/build/qemu-system-riscv64
CROSS_CC_GUEST_CFLAGS=
